# Site settings
title: Prabhat Ranjan
general_email: mailprabhatr@gmail.com
academic_email: prabhatr@iitb.ac.in

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "/~prabhatr" # the subpath of your site, e.g. /blog/

url: "https://prabhat496.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: prabhat496
linkedin_username: prabhat-ranjan-9595bb151
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title

#plugins:
#       - jekyll-google-photos
